CCMSG-2220: Updated jackson dependency to resolve CVE-2022-42003 and CVE-2022-42004
confluentinc/kafka-connect-elasticsearch pull request #661
Opened 2022-11-17 07:49 UTC by arihant-confluent

## Problem
https://confluentinc.atlassian.net/browse/CCMSG-2220

## Solution
Updated jackson dependency to resolve CVE-2022-42003 and CVE-2022-42004

##### Does this solution apply anywhere else?
- [ ] yes
- [x] no

##### If yes, where?

## Test Strategy

##### Testing done:
- [x] Unit tests
- [x] Integration tests
- [ ] System tests
- [ ] Manual tests

## Release Plan

2022-11-17 08:33 UTC, snehashisp approved these changes
LGTM

2022-11-17 08:44 UTC, pkuntalteam1 requested changes
jackson version have been updated in 'common' itself. We can remove jackson dependency completely from this pom and upgrade common version.

2022-11-17 09:11 UTC, arihant-confluent commented
> jackson data-bind dependency have been updated to 2.13.4 in 'common' itself. We can remove jackson dependency completely from this pom and upgrade common version. https://github.com/confluentinc/common/pull/485/files

we need to upgrade to v2.14.0 or later https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html

2022-11-18 07:24 UTC, pkuntalteam1 approved these changes

2022-11-18 08:48 UTC, merged